#!/usr/bin/env node
/**
 * build-schema.mjs
 *
 * Regenerates the JSON-LD `mainEntity` (ItemList) block inside index.html and
 * en/index.html from the wishlist product JSON files. The product JSON files
 * are the single source of truth; the JSON-LD in the HTML files is generated
 * output between markers and must not be edited manually:
 *
 *   <!-- JSON-LD:BEGIN (generated by scripts/build-schema.mjs - do not edit manually) -->
 *   <script type="application/ld+json" id="wishlist-schema"> ... </script>
 *   <!-- JSON-LD:END -->
 *
 * Top-level WebPage fields (name, description, isPartOf, about,
 * primaryImageOfPage, inLanguage, @id) are preserved from the existing block
 * in each HTML file. Only the ItemList is rebuilt from the product data.
 *
 * Usage: node scripts/build-schema.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SITE_URL = "https://lsd.cannachris.de/";

const MARKER_BEGIN =
  "<!-- JSON-LD:BEGIN (generated by scripts/build-schema.mjs - do not edit manually) -->";
const MARKER_END = "<!-- JSON-LD:END -->";

const SCHEMA_BLOCK_REGEX = new RegExp(
  "(?:[ \\t]*" +
    escapeRegExp(MARKER_BEGIN) +
    "\\s*)?" +
    '[ \\t]*<script type="application\\/ld\\+json" id="wishlist-schema">\\s*' +
    "([\\s\\S]*?)" +
    "\\s*<\\/script>" +
    "(?:\\s*[ \\t]*" +
    escapeRegExp(MARKER_END) +
    ")?",
);

const TARGETS = [
  { html: "index.html", products: "wishlist-products.json" },
  { html: join("en", "index.html"), products: "wishlist-products.en.json" },
];

// Google's site-name signal: WebSite.name must match og:site_name
// ("Lazy Stoner Donator"); the person behind it stays "Cannachris".
const WEBSITE = {
  "@type": "WebSite",
  "@id": SITE_URL + "#website",
  name: "Lazy Stoner Donator",
  alternateName: "Cannachris",
  url: SITE_URL,
};

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function loadJson(relativePath) {
  return JSON.parse(readFileSync(join(ROOT, relativePath), "utf8"));
}

function buildListItem(product, position) {
  const item = {
    "@type": "Thing",
    "@id": SITE_URL + "#" + product.adId,
    name: product.title,
    url: product.url,
    image: product.image,
    description: product.description || product.title,
    identifier: product.adId,
  };

  const keywords = Array.isArray(product.imageKeywords)
    ? product.imageKeywords
    : [];
  if (keywords.length > 0) {
    item.keywords = keywords.join(", ");
    item.about = keywords.map((keyword) => ({
      "@type": "Thing",
      name: keyword,
    }));
  }

  if (product.seoIntent) {
    item.alternateName = product.seoIntent;
  }

  if (product.audienceLabel) {
    item.disambiguatingDescription = product.audienceLabel;
  }

  return { "@type": "ListItem", position, item };
}

function buildItemList(products, existingMainEntity) {
  return {
    "@type": "ItemList",
    name:
      (existingMainEntity && existingMainEntity.name) || "Lazy Stoner Donator",
    numberOfItems: products.length,
    itemListElement: products.map((product, index) =>
      buildListItem(product, index + 1),
    ),
  };
}

function renderBlock(schema) {
  // Minified on purpose: JSON-LD must stay inline for SEO, but it is
  // generated output - a single line keeps the HTML files small and the
  // markup readable. Edit wishlist-products.json, then rerun this script.
  return (
    MARKER_BEGIN +
    "\n" +
    '    <script type="application/ld+json" id="wishlist-schema">' +
    JSON.stringify(schema) +
    "</script>\n" +
    "    " +
    MARKER_END
  );
}

let failures = 0;

for (const target of TARGETS) {
  const htmlPath = join(ROOT, target.html);
  const html = readFileSync(htmlPath, "utf8");
  const match = html.match(SCHEMA_BLOCK_REGEX);

  if (!match) {
    console.error(
      'ERROR: No JSON-LD block with id "wishlist-schema" found in ' +
        target.html,
    );
    failures += 1;
    continue;
  }

  let existingSchema;
  try {
    existingSchema = JSON.parse(match[1]);
  } catch (error) {
    console.error(
      "ERROR: Existing JSON-LD in " +
        target.html +
        " is not valid JSON: " +
        error.message,
    );
    failures += 1;
    continue;
  }

  const products = loadJson(target.products);
  const schema = Object.assign({}, existingSchema, {
    isPartOf: WEBSITE,
    mainEntity: buildItemList(products, existingSchema.mainEntity),
  });

  const updated = html.replace(SCHEMA_BLOCK_REGEX, () => renderBlock(schema));
  writeFileSync(htmlPath, updated);

  console.log(
    target.html +
      ": regenerated JSON-LD ItemList with " +
      products.length +
      " items from " +
      target.products,
  );
}

if (failures > 0) {
  process.exitCode = 1;
}
