#!/usr/bin/env node
/**
 * build-schema.mjs
 *
 * Regenerates the JSON-LD `mainEntity` (ItemList) block inside index.html and
 * en/index.html from the wishlist product JSON files. The product JSON files
 * are the single source of truth; the JSON-LD in the HTML files is generated
 * output between markers and must not be edited manually:
 *
 *   <!-- JSON-LD:BEGIN (generated by scripts/build-schema.mjs - do not edit manually) -->
 *   <script type="application/ld+json" id="wishlist-schema"> ... </script>
 *   <!-- JSON-LD:END -->
 *
 * The schema is emitted as a single @graph with five sibling nodes:
 * WebSite (site-name signal), Organization with logo (Logo enhancement),
 * Person (creator entity, public persona only), WebPage (existing fields
 * are preserved) and BreadcrumbList (breadcrumb rich result). Organization
 * and Person share the sameAs social profiles mirrored from the visible
 * footer links. The ItemList stays the WebPage mainEntity and is rebuilt
 * from the product data. Product/Offer markup is deliberately NOT emitted:
 * prices are not visible in the UI and the site is not the merchant, so
 * product rich results would violate Google's structured data guidelines.
 *
 * Usage: node scripts/build-schema.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SITE_URL = "https://lsd.cannachris.de/";

const MARKER_BEGIN =
  "<!-- JSON-LD:BEGIN (generated by scripts/build-schema.mjs - do not edit manually) -->";
const MARKER_END = "<!-- JSON-LD:END -->";

const SCHEMA_BLOCK_REGEX = new RegExp(
  "(?:[ \\t]*" +
    escapeRegExp(MARKER_BEGIN) +
    "\\s*)?" +
    '[ \\t]*<script type="application\\/ld\\+json" id="wishlist-schema">\\s*' +
    "([\\s\\S]*?)" +
    "\\s*<\\/script>" +
    "(?:\\s*[ \\t]*" +
    escapeRegExp(MARKER_END) +
    ")?",
);

const TARGETS = [
  {
    html: "index.html",
    products: "wishlist-products.json",
    pageUrl: SITE_URL,
    breadcrumbName: "Lazy Stoner Donator",
  },
  {
    html: join("en", "index.html"),
    products: "wishlist-products.en.json",
    pageUrl: SITE_URL + "en/",
    breadcrumbName: "Lazy Stoner Donator – Wishlist",
  },
];

// Google's site-name signal: WebSite.name must match og:site_name
// ("Lazy Stoner Donator"); the person behind it stays "Cannachris".
const WEBSITE = {
  "@type": "WebSite",
  "@id": SITE_URL + "#website",
  name: "Lazy Stoner Donator",
  alternateName: "Cannachris",
  url: SITE_URL,
};

// Public social profiles of the Cannachris persona, mirrored from the
// visible footer links in index.html. They are the entity-resolution
// backbone (sameAs) for AI overviews and knowledge panels.
const SOCIAL_PROFILES = [
  "https://cannachris.de/",
  "https://www.instagram.com/c4nnachris/",
  "https://www.tiktok.com/@cann4chris",
  "https://www.twitch.tv/c4nnachris",
  "https://x.com/chooom",
  "https://www.youtube.com/channel/UCD3wuH5mUzr5el3KNZM9fOw",
  "https://www.facebook.com/c4nnachris",
];

// Organization node with a logo that meets Google's image guidelines
// (PNG, 192x192, crawlable). Eligible for the Logo knowledge-panel
// enhancement instead of a guessed favicon.
const ORGANIZATION = {
  "@type": "Organization",
  "@id": SITE_URL + "#organization",
  name: "Cannachris",
  url: "https://cannachris.de/",
  logo: {
    "@type": "ImageObject",
    "@id": SITE_URL + "#logo",
    url: SITE_URL + "icon-192.png",
    width: 192,
    height: 192,
    caption: "Cannachris",
  },
  sameAs: SOCIAL_PROFILES,
};

// Person node for the creator behind the list. Uses only the public
// persona ("Cannachris") - no private real-world data is asserted.
const PERSON = {
  "@type": "Person",
  "@id": SITE_URL + "#person",
  name: "Cannachris",
  url: "https://cannachris.de/",
  image: SITE_URL + "assets/images/cannachris-lazy-stoner-donator.png",
  sameAs: SOCIAL_PROFILES,
};

function buildBreadcrumbList(pageUrl, breadcrumbName) {
  return {
    "@type": "BreadcrumbList",
    "@id": pageUrl + "#breadcrumb",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Cannachris",
        item: "https://cannachris.de/",
      },
      {
        "@type": "ListItem",
        position: 2,
        name: breadcrumbName,
        item: pageUrl,
      },
    ],
  };
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function loadJson(relativePath) {
  return JSON.parse(readFileSync(join(ROOT, relativePath), "utf8"));
}

function buildListItem(product, position) {
  const item = {
    "@type": "Thing",
    "@id": SITE_URL + "#" + product.adId,
    name: product.title,
    url: product.url,
    image: product.image,
    description: product.description || product.title,
    identifier: product.adId,
  };

  const keywords = Array.isArray(product.imageKeywords)
    ? product.imageKeywords
    : [];
  if (keywords.length > 0) {
    item.keywords = keywords.join(", ");
    item.about = keywords.map((keyword) => ({
      "@type": "Thing",
      name: keyword,
    }));
  }

  if (product.seoIntent) {
    item.alternateName = product.seoIntent;
  }

  if (product.audienceLabel) {
    item.disambiguatingDescription = product.audienceLabel;
  }

  return { "@type": "ListItem", position, item };
}

function buildItemList(products, existingMainEntity) {
  return {
    "@type": "ItemList",
    name:
      (existingMainEntity && existingMainEntity.name) || "Lazy Stoner Donator",
    numberOfItems: products.length,
    itemListElement: products.map((product, index) =>
      buildListItem(product, index + 1),
    ),
  };
}

// Reads the current block and returns the schema in @graph shape, no matter
// whether the block is still a flat WebPage object (legacy) or already a
// @graph document. The WebPage node keeps its existing descriptive fields.
function extractWebPageFields(existingSchema) {
  if (existingSchema && Array.isArray(existingSchema["@graph"])) {
    const webPage = existingSchema["@graph"].find(
      (node) => node && node["@type"] === "WebPage",
    );
    if (webPage) {
      const fields = Object.assign({}, webPage);
      delete fields.isPartOf;
      delete fields.publisher;
      delete fields.breadcrumb;
      delete fields.mainEntity;
      delete fields.author;
      delete fields.creator;
      return fields;
    }
  }

  const fields = Object.assign({}, existingSchema || {});
  delete fields["@context"];
  delete fields.isPartOf;
  delete fields.publisher;
  delete fields.breadcrumb;
  delete fields.author;
  delete fields.creator;
  const webPageFields = Object.assign({}, fields);
  delete webPageFields.mainEntity;
  return webPageFields;
}

function existingItemList(existingSchema) {
  if (existingSchema && Array.isArray(existingSchema["@graph"])) {
    const webPage = existingSchema["@graph"].find(
      (node) => node && node["@type"] === "WebPage",
    );
    return webPage ? webPage.mainEntity : null;
  }
  return existingSchema ? existingSchema.mainEntity : null;
}

function renderBlock(schema) {
  // Minified on purpose: JSON-LD must stay inline for SEO, but it is
  // generated output - a single line keeps the HTML files small and the
  // markup readable. Edit wishlist-products.json, then rerun this script.
  return (
    MARKER_BEGIN +
    "\n" +
    '    <script type="application/ld+json" id="wishlist-schema">' +
    JSON.stringify(schema) +
    "</script>\n" +
    "    " +
    MARKER_END
  );
}

let failures = 0;

for (const target of TARGETS) {
  const htmlPath = join(ROOT, target.html);
  const html = readFileSync(htmlPath, "utf8");
  const match = html.match(SCHEMA_BLOCK_REGEX);

  if (!match) {
    console.error(
      'ERROR: No JSON-LD block with id "wishlist-schema" found in ' +
        target.html,
    );
    failures += 1;
    continue;
  }

  let existingSchema;
  try {
    existingSchema = JSON.parse(match[1]);
  } catch (error) {
    console.error(
      "ERROR: Existing JSON-LD in " +
        target.html +
        " is not valid JSON: " +
        error.message,
    );
    failures += 1;
    continue;
  }

  const products = loadJson(target.products);
  const breadcrumbList = buildBreadcrumbList(
    target.pageUrl,
    target.breadcrumbName,
  );
  const webPage = Object.assign({}, extractWebPageFields(existingSchema), {
    "@type": "WebPage",
    isPartOf: { "@id": WEBSITE["@id"] },
    publisher: { "@id": ORGANIZATION["@id"] },
    author: { "@id": PERSON["@id"] },
    creator: { "@id": PERSON["@id"] },
    breadcrumb: { "@id": breadcrumbList["@id"] },
    mainEntity: buildItemList(products, existingItemList(existingSchema)),
  });
  const schema = {
    "@context": "https://schema.org",
    "@graph": [WEBSITE, ORGANIZATION, PERSON, webPage, breadcrumbList],
  };

  const updated = html.replace(SCHEMA_BLOCK_REGEX, () => renderBlock(schema));
  writeFileSync(htmlPath, updated);

  console.log(
    target.html +
      ": regenerated JSON-LD ItemList with " +
      products.length +
      " items from " +
      target.products,
  );
}

if (failures > 0) {
  process.exitCode = 1;
}
